// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `error_to_string`, `lock`, `selected_pages`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `RhwpCommand`, `RhwpSessionInner`

Future<RhwpSession> openBytes({required List<int> bytes, String? fileName}) =>
    RustLib.instance.api.crateApiRhwpOpenBytes(
      bytes: bytes,
      fileName: fileName,
    );

Future<RhwpSession> createEmpty({String? fileName}) =>
    RustLib.instance.api.crateApiRhwpCreateEmpty(fileName: fileName);

Future<String> rhwpVersion() => RustLib.instance.api.crateApiRhwpRhwpVersion();

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<RhwpSession>>
abstract class RhwpSession implements RustOpaqueInterface {
  Future<String> applyCommand({required String commandJson});

  Future<void> close();

  Future<RhwpDocumentInfo> documentInfo();

  Future<Uint8List> exportDocx();

  Future<Uint8List> exportHwp();

  Future<Uint8List> exportHwpx();

  Future<Uint8List> exportPdf();

  Future<String> extractMarkdown({int? page});

  Future<String> extractText({int? page});

  Future<int> pageCount();

  Future<String> pageLayerTree({required int page});

  Future<String> renderPageSvg({required int page});
}

class RhwpDocumentInfo {
  final int pageCount;
  final String sourceFormat;
  final String? fileName;
  final String rawJson;

  const RhwpDocumentInfo({
    required this.pageCount,
    required this.sourceFormat,
    this.fileName,
    required this.rawJson,
  });

  @override
  int get hashCode =>
      pageCount.hashCode ^
      sourceFormat.hashCode ^
      fileName.hashCode ^
      rawJson.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RhwpDocumentInfo &&
          runtimeType == other.runtimeType &&
          pageCount == other.pageCount &&
          sourceFormat == other.sourceFormat &&
          fileName == other.fileName &&
          rawJson == other.rawJson;
}
